language: cpp

before_install:
 # newer gcc
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 # qt5
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
 - sudo apt-get update -qq
 # g++ 4.8 for std=c++11
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 # additional headerfiles
 - sudo apt-get install libXxf86vm-dev libXi-dev libudev-dev libXcursor-dev
 - sudo apt-get install -f qtbase5-dev qt5-default qttools5-dev-tools libqt5opengl5-dev

script:
 - qmake -r QMAKE_CXX=g++-4.8 QMAKE_CC=gcc-4.8
 - make

os:
  - linux
